[package]
name = "tauri-plugin-analytics"
version = "0.1.0"
authors = ["You"]
edition = "2024"
exclude = ["/js", "/node_modules"]
links = "tauri-plugin-analytics"
description = ""

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dev-dependencies]
specta-typescript = { workspace = true }
tauri-plugin-store = { workspace = true }
tokio = { workspace = true, features = ["macros"] }

[dependencies]
meetspace-analytics = { workspace = true }
meetspace-host = { workspace = true }

tauri-plugin-misc = { workspace = true }
tauri-plugin-store2 = { workspace = true }

tauri = { workspace = true, features = ["test"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true }
strum = { workspace = true, features = ["derive"] }

thiserror = { workspace = true }
