[package]
name = "tauri-plugin-calendar"
version = "0.1.0"
authors = ["You"]
edition = "2024"
exclude = ["/js", "/node_modules"]
links = "tauri-plugin-calendar"
description = ""

[dependencies]
meetspace-calendar = { workspace = true, features = ["specta"] }
meetspace-calendar-interface = { workspace = true }

tauri = { workspace = true, features = ["test"] }
tauri-plugin-auth = { workspace = true }
tauri-plugin-permissions = { workspace = true }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["chrono"] }
thiserror = { workspace = true }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dev-dependencies]
specta-typescript = { workspace = true }
