// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async render(tpl: Template) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|render", { tpl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderCustom(templateContent: string, ctx: Partial<{ [key in string]: JsonValue }>) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|render_custom", { templateContent, ctx }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renderSupport(tpl: SupportTemplate) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|render_support", { tpl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTemplateSource(template: EditableTemplate) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("plugin:template|get_template_source", { template }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AccountInfo = { userId: string; email: string | null; fullName: string | null; avatarUrl: string | null; stripeCustomerId: string | null }
export type ActivityCaptureSystem = { language: string | null }
export type ActivityCaptureUser = { appName: string; windowTitle: string | null; reason: string; fingerprint: string }
export type BugReport = { description: string; platform: string; arch: string; osVersion: string; appVersion: string; source: string }
export type ChatSystem = { language: string | null }
export type ContextBlock = { contexts: SessionContext[] }
export type DailySummaryAnalysis = { time: string; appName: string; windowTitle: string | null; reason: string; summary: string }
export type DailySummaryAppStat = { appName: string; count: number }
export type DailySummaryStats = { signalCount: number; screenshotCount: number; analysisCount: number; uniqueAppCount: number; firstSignal: string | null; lastSignal: string | null }
export type DailySummarySystem = { language: string | null }
export type DailySummaryUser = { date: string; timezone: string | null; stats: DailySummaryStats; topApps: DailySummaryAppStat[]; analyses: DailySummaryAnalysis[]; totalAnalysisCount: number; existingSummary: string | null }
export type DeviceInfo = { platform: string; arch: string; osVersion: string; appVersion: string; buildHash?: string | null; locale?: string | null }
export type EditableTemplate = "enhanceUser" | "titleUser"
export type EnhanceSystem = { language: string | null }
export type EnhanceTemplate = { title: string; description: string | null; sections: TemplateSection[] }
export type EnhanceUser = { session: Session; participants: Participant[]; template: EnhanceTemplate | null; transcripts: Transcript[]; preMeetingMemo: string; postMeetingMemo: string }
export type Event = { name: string }
export type EventContactCandidate = { name: string | null; email: string | null; isCurrentUser: boolean; isOrganizer: boolean }
export type EventContactSystem = Record<string, never>
export type EventContactUser = { title: string | null; description: string | null; candidates: EventContactCandidate[] }
export type FeatureRequest = { description: string; platform: string; arch: string; osVersion: string; appVersion: string; source: string }
export type Grammar = { task: "enhance"; sections: string[] | null } | { task: "title" } | { task: "tags" } | { task: "email-to-name" }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LogAnalysis = { summarySection: string; tail: string }
export type ModelInfo = { llmProvider?: string | null; llmModel?: string | null; sttProvider?: string | null; sttModel?: string | null }
export type Participant = { name: string; jobTitle: string | null }
export type Segment = { text: string; speaker: string }
export type Session = { title: string | null; startedAt: string | null; endedAt: string | null; event: Event | null }
export type SessionContext = { title: string | null; date: string | null; rawContent: string | null; enhancedContent: string | null; transcript: Transcript | null; participants: Participant[]; event: Event | null }
export type SupportContext = { account: AccountInfo | null; device: DeviceInfo; models?: ModelInfo | null }
export type SupportTemplate = { supportContext: SupportContext } | { bugReport: BugReport } | { featureRequest: FeatureRequest } | { logAnalysis: LogAnalysis }
export type Template = { activityCaptureSystem: ActivityCaptureSystem } | { activityCaptureUser: ActivityCaptureUser } | { dailySummarySystem: DailySummarySystem } | { dailySummaryUser: DailySummaryUser } | { enhanceSystem: EnhanceSystem } | { enhanceUser: EnhanceUser } | { eventContactSystem: EventContactSystem } | { eventContactUser: EventContactUser } | { titleSystem: TitleSystem } | { titleUser: TitleUser } | { chatSystem: ChatSystem } | { contextBlock: ContextBlock } | { toolSearchSessions: ToolSearchSessions } | { transcriptPatchSystem: TranscriptPatchSystem } | { transcriptPatchUser: TranscriptPatchUser }
export type TemplateSection = { title: string; description: string | null }
export type TitleSystem = { language: string | null }
export type TitleUser = { enhancedNote: string }
export type ToolSearchSessionItem = { id: string; title: string | null; excerpt: string | null; score: number; createdAt: number | null; sessionContext: SessionContext | null }
export type ToolSearchSessions = { query: string; results: ToolSearchSessionItem[] }
export type Transcript = { segments: Segment[]; startedAt: number | null; endedAt: number | null }
export type TranscriptPatchSystem = { language: string | null }
export type TranscriptPatchUser = { transcriptJson: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
