import type { TablesSchema } from "tinybase/with-schemas";

import type { InferTinyBaseSchema } from "./shared";
import {
  calendarSchema,
  chatGroupSchema,
  chatMessageSchema,
  dailyNoteSchema,
  enhancedNoteSchema,
  eventSchema,
  generalSchema,
  humanSchema,
  mappingMentionSchema,
  mappingSessionParticipantSchema,
  mappingTagSessionSchema,
  organizationSchema,
  sessionKeyFactsSchema,
  sessionSchema,
  tagSchema,
  taskSchema,
  transcriptSchema,
} from "./zod";

export const tableSchemaForTinybase = {
  sessions: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    folder_id: { type: "string" },
    event_json: { type: "string" },
    title: { type: "string" },
    raw_md: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof sessionSchema>,
  transcripts: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    session_id: { type: "string" },
    started_at: { type: "number" },
    ended_at: { type: "number" },
    words: { type: "string" },
    speaker_hints: { type: "string" },
    memo_md: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof transcriptSchema>,
  humans: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    name: { type: "string" },
    email: { type: "string" },
    phone: { type: "string" },
    org_id: { type: "string" },
    job_title: { type: "string" },
    linkedin_username: { type: "string" },
    memo: { type: "string" },
    pinned: { type: "boolean" },
    pin_order: { type: "number" },
  } as const satisfies InferTinyBaseSchema<typeof humanSchema>,
  organizations: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    name: { type: "string" },
    pinned: { type: "boolean" },
    pin_order: { type: "number" },
  } as const satisfies InferTinyBaseSchema<typeof organizationSchema>,
  calendars: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    tracking_id_calendar: { type: "string" },
    name: { type: "string" },
    enabled: { type: "boolean" },
    provider: { type: "string" },
    source: { type: "string" },
    color: { type: "string" },
    connection_id: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof calendarSchema>,
  events: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    tracking_id_event: { type: "string" },
    calendar_id: { type: "string" },
    title: { type: "string" },
    started_at: { type: "string" },
    ended_at: { type: "string" },
    location: { type: "string" },
    meeting_link: { type: "string" },
    description: { type: "string" },
    note: { type: "string" },
    recurrence_series_id: { type: "string" },
    has_recurrence_rules: { type: "boolean" },
    is_all_day: { type: "boolean" },
    provider: { type: "string" },
    participants_json: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof eventSchema>,
  mapping_session_participant: {
    user_id: { type: "string" },
    session_id: { type: "string" },
    human_id: { type: "string" },
    source: { type: "string" },
  } as const satisfies InferTinyBaseSchema<
    typeof mappingSessionParticipantSchema
  >,
  tags: {
    user_id: { type: "string" },
    name: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof tagSchema>,
  mapping_tag_session: {
    user_id: { type: "string" },
    tag_id: { type: "string" },
    session_id: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof mappingTagSessionSchema>,
  mapping_mention: {
    user_id: { type: "string" },
    source_id: { type: "string" },
    source_type: { type: "string" },
    target_id: { type: "string" },
    target_type: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof mappingMentionSchema>,
  chat_groups: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    title: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof chatGroupSchema>,
  chat_messages: {
    user_id: { type: "string" },
    created_at: { type: "string" },
    chat_group_id: { type: "string" },
    role: { type: "string" },
    content: { type: "string" },
    metadata: { type: "string" },
    parts: { type: "string" },
    status: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof chatMessageSchema>,
  enhanced_notes: {
    user_id: { type: "string" },
    session_id: { type: "string" },
    content: { type: "string" },
    template_id: { type: "string" },
    position: { type: "number" },
    title: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof enhancedNoteSchema>,
  session_key_facts: {
    user_id: { type: "string" },
    session_id: { type: "string" },
    created_at: { type: "string" },
    updated_at: { type: "string" },
    content: { type: "string" },
    source_hash: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof sessionKeyFactsSchema>,
  tasks: {
    user_id: { type: "string" },
    task_id: { type: "string" },
    source_id: { type: "string" },
    source_type: { type: "string" },
    source_order: { type: "number" },
    status: { type: "string" },
    text_preview: { type: "string" },
    body_json: { type: "string" },
    due_date: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof taskSchema>,
  daily_notes: {
    user_id: { type: "string" },
    date: { type: "string" },
    content: { type: "string" },
  } as const satisfies InferTinyBaseSchema<typeof dailyNoteSchema>,
} as const satisfies TablesSchema;

export const valueSchemaForTinybase = {
  user_id: { type: "string" },
  autostart: { type: "boolean" },
  auto_stop_meetings: { type: "boolean" },
  auto_start_scheduled_meetings: { type: "boolean" },
  floating_bar_enabled: { type: "boolean" },
  sidebar_timeline_enabled: { type: "boolean" },
  save_recordings: { type: "boolean" },
  audio_retention: { type: "string" },
  notification_event: { type: "boolean" },
  notification_detect: { type: "boolean" },
  respect_dnd: { type: "boolean" },
  quit_intercept: { type: "boolean" },
  telemetry_consent: { type: "boolean" },
  ai_language: { type: "string" },
  spoken_languages: { type: "string" },
  ignored_platforms: { type: "string" },
  included_platforms: { type: "string" },
  ignored_events: { type: "string" },
  ignored_recurring_series: { type: "string" },
  current_llm_provider: { type: "string" },
  current_llm_model: { type: "string" },
  current_stt_provider: { type: "string" },
  current_stt_model: { type: "string" },
  on_device_transcription_mode: { type: "string" },
  theme: { type: "string" },
} as const satisfies InferTinyBaseSchema<typeof generalSchema>;
