[package]
name = "local-llm-core"
version = "0.1.0"
edition = "2024"

[features]
specta = ["dep:specta"]

[dependencies]
meetspace-file = { workspace = true }
meetspace-gguf = { workspace = true }
meetspace-lmstudio = { workspace = true }
meetspace-local-model = { workspace = true }

axum = { workspace = true }
dirs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true, features = ["cors"] }
tracing = { workspace = true }

specta = { workspace = true, optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
meetspace-llm-cactus = { workspace = true }
