packages:
  - apps/*
  - packages/*
  - plugins/*
  - examples/plugins/*
  - e2e/*

publicHoistPattern:
  - "!bun-types"
  - "!@types/bun"

patchedDependencies:
  "@tiptap/extension-paragraph@3.20.1": patches/@tiptap__extension-paragraph@3.20.1.patch

overrides:
  "@tiptap/extension-paragraph": "3.20.1"
  "@tiptap/extension-blockquote": "3.20.1"
  "@tiptap/extension-bold": "3.20.1"
  "@tiptap/extension-code": "3.20.1"
  "@tiptap/extension-code-block": "3.20.1"
  "@tiptap/extension-document": "3.20.1"
  "@tiptap/extension-hard-break": "3.20.1"
  "@tiptap/extension-heading": "3.20.1"
  "@tiptap/extension-horizontal-rule": "3.20.1"
  "@tiptap/extension-italic": "3.20.1"
  "@tiptap/extension-text": "3.20.1"
  "@tiptap/extension-strike": "3.20.1"
  "@tiptap/extension-list": "3.20.1"
  "@tiptap/extension-bubble-menu": "3.20.1"
  "@tiptap/extension-floating-menu": "3.20.1"
  "@tiptap/extensions": "3.20.1"
  prosemirror-view: "1.41.7"
  lightningcss: "1.30.1"

peerDependencyRules:
  allowedVersions:
    motion: "11"
    react: "19"
    "@lobehub/ui": "3.4.0"
    unist-util-visit: "5"
    esbuild: "0.25"

allowBuilds:
  "@parcel/watcher": true
  "@sentry/cli": true
  cbor-extract: true
  core-js: true
  dprint: true
  edgedriver: true
  esbuild: true
  geckodriver: true
  protobufjs: true
  sharp: true
  unix-dgram: true
