[package]
name = "api-messenger"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-api-error = { workspace = true }
meetspace-http = { workspace = true }
meetspace-slack-web = { workspace = true }
meetspace-teems = { workspace = true }

axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
