[package]
name = "api-calendar"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-api-auth = { workspace = true }
meetspace-api-error = { workspace = true }
meetspace-api-nango = { workspace = true }
meetspace-google-calendar = { workspace = true, features = ["utoipa"] }
meetspace-nango = { workspace = true }
meetspace-outlook-calendar = { workspace = true, features = ["utoipa"] }

chrono = { workspace = true, features = ["serde"] }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
