// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async showNotification(v: Notification): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:notification|show_notification", {
          v,
        }),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
  async clearNotifications(): Promise<Result<null, string>> {
    try {
      return {
        status: "ok",
        data: await TAURI_INVOKE("plugin:notification|clear_notifications"),
      };
    } catch (e) {
      if (e instanceof Error) throw e;
      else return { status: "error", error: e as any };
    }
  },
};

/** user-defined events **/

export const events = __makeEvents__<{
  notificationEvent: NotificationEvent;
}>({
  notificationEvent: "plugin:notification:notification-event",
});

/** user-defined constants **/

/** user-defined types **/

export type Duration = { secs: number; nanos: number };
export type EventDetails = {
  what: string;
  timezone: string | null;
  location: string | null;
};
export type Notification = {
  key: string | null;
  title: string;
  message: string;
  timeout: Duration | null;
  source: NotificationSource | null;
  start_time: number | null;
  participants: Participant[] | null;
  event_details: EventDetails | null;
  action_label: string | null;
  action_variant: NotificationActionVariant | null;
  options: string[] | null;
  footer: NotificationFooter | null;
  icon: NotificationIcon | null;
};
export type NotificationActionVariant = "default" | "destructive";
export type NotificationEvent =
  | {
      type: "notification_confirm";
      key: string;
      source: NotificationSource | null;
    }
  | {
      type: "notification_accept";
      key: string;
      source: NotificationSource | null;
    }
  | {
      type: "notification_dismiss";
      key: string;
      source: NotificationSource | null;
    }
  | {
      type: "notification_timeout";
      key: string;
      source: NotificationSource | null;
    }
  | {
      type: "notification_option_selected";
      key: string;
      source: NotificationSource | null;
      selected_index: number;
    }
  | {
      type: "notification_footer_action";
      key: string;
      source: NotificationSource | null;
    };
export type NotificationFooter = {
  text: string;
  actionLabel: string;
  icon: NotificationIcon | null;
};
export type NotificationIcon =
  | { type: "hidden" }
  | { type: "bundle_id"; bundle_id: string }
  | { type: "path"; path: string }
  | {
      type: "overlay";
      base: NotificationIconAsset;
      badge: NotificationIconAsset;
    };
export type NotificationIconAsset =
  | { type: "app_icon" }
  | { type: "calendar" }
  | { type: "bundle_id"; bundle_id: string }
  | { type: "path"; path: string };
export type NotificationSource =
  | { type: "calendar_event"; event_id: string }
  | { type: "session"; session_id: string }
  | {
      type: "mic_detected";
      app_names: string[];
      app_ids?: string[];
      event_ids?: string[];
    };
export type Participant = {
  name: string | null;
  email: string;
  status: ParticipantStatus;
};
export type ParticipantStatus = "Accepted" | "Maybe" | "Declined";

/** tauri-specta globals **/

import {
  invoke as TAURI_INVOKE,
  Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
  listen: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
  once: (
    cb: TAURI_API_EVENT.EventCallback<T>,
  ) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
  | { status: "ok"; data: T }
  | { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
  mappings: Record<keyof T, string>,
) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>;
      };
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T];

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case "listen":
                return (arg: any) => TAURI_API_EVENT.listen(name, arg);
              case "once":
                return (arg: any) => TAURI_API_EVENT.once(name, arg);
              case "emit":
                return (arg: any) => TAURI_API_EVENT.emit(name, arg);
            }
          },
        });
      },
    },
  );
}
