[package]
name = "notification"
version = "0.1.0"
edition = "2024"

[features]
default = ["legacy"]
legacy = ["dep:meetspace-notification-macos", "dep:meetspace-notification-linux"]

[dependencies]
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }

meetspace-notification-interface = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
meetspace-notification-macos = { path = "../notification-macos", package = "notification-macos", optional = true }

[target.'cfg(target_os = "linux")'.dependencies]
meetspace-notification-linux = { path = "../notification-linux", package = "notification-linux", optional = true }
