[package]
name = "tauri-plugin-importer"
version = "0.1.0"
authors = ["You"]
edition = "2024"
exclude = ["/node_modules"]
links = "tauri-plugin-importer"
description = ""

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dev-dependencies]
dirs = { workspace = true }
specta-typescript = { workspace = true }
tempfile = { workspace = true }

[dependencies]
legacy-db-parser = { workspace = true }
meetspace-granola = { workspace = true }
meetspace-importer-core = { workspace = true }

tauri-plugin-settings = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true }
tauri = { workspace = true, features = ["test"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }

chrono = { workspace = true }
dirs = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "time"] }
uuid = { workspace = true, features = ["v4", "v5"] }
