[package]
name = "tauri-plugin-template"
version = "0.1.0"
authors = ["You"]
edition = "2024"
exclude = ["/node_modules"]
links = "tauri-plugin-template"
description = ""

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }

[dev-dependencies]
specta-typescript = { workspace = true }

[dependencies]
meetspace-gbnf = { workspace = true }
meetspace-template-app = { workspace = true }
meetspace-template-app-legacy = { workspace = true }
meetspace-template-support = { workspace = true }

serde_json = { workspace = true }
tracing = { workspace = true }

specta = { workspace = true, features = ["serde_json"] }
tauri = { workspace = true, features = ["test"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }
