[package]
name = "audio-norm"
version = "0.1.0"
edition = "2024"

[dependencies]
audioadapter-buffers = "2.0"
meetspace-afconvert = { workspace = true }
meetspace-audio-utils = { workspace = true }
meetspace-mp3 = { workspace = true }
meetspace-resampler = { workspace = true }

rodio = { workspace = true, features = ["symphonia-all"] }
thiserror = { workspace = true }

[dev-dependencies]
assert_fs = "1"
meetspace-data = { workspace = true }
