[package]
name = "db-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
meetspace-importer-core = { workspace = true }
owhisper-interface = { workspace = true }

chrono = { version = "0.4", features = ["serde"] }
rusqlite = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }

htmd = { workspace = true }

[dev-dependencies]
dirs = { workspace = true }
tokio = { workspace = true }
