[package]
name = "fs-sync-core"
version = "0.1.0"
edition = "2024"

[features]
default = []
tauri-event = ["dep:tauri-specta"]

[dependencies]
meetspace-audio-norm = { workspace = true }
meetspace-audio-utils = { workspace = true }
meetspace-frontmatter = { workspace = true }
meetspace-fs-format = { workspace = true }
meetspace-tiptap = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
specta = { workspace = true, features = ["derive", "serde_json"] }
tauri-specta = { workspace = true, optional = true, features = ["derive"] }

glob = "0.3"
rayon = { workspace = true }

chrono = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
assert_fs = "1"
criterion = { workspace = true }
meetspace-data = { workspace = true }
predicates = "3"
tempfile = { workspace = true }

[[bench]]
name = "audio_import"
harness = false
