[package]
name = "audio-chunking"
version = "0.1.0"
edition = "2024"

[features]
default = ["vad"]
vad = [
  "dep:futures-util",
  "dep:meetspace-audio-interface",
  "dep:meetspace-onnx",
  "dep:meetspace-vad",
  "dep:pin-project",
]
segmentation = []

[dev-dependencies]
futures-util = { workspace = true }
hound = { workspace = true }
meetspace-data = { workspace = true }
rodio = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[[example]]
name = "chunking"
required-features = ["vad"]

[dependencies]
meetspace-audio-interface = { workspace = true, optional = true }
meetspace-onnx = { workspace = true, optional = true }
meetspace-vad = { workspace = true, features = ["silero-onnx"], optional = true }

futures-util = { workspace = true, optional = true }
pin-project = { workspace = true, optional = true }
thiserror = { workspace = true }
