[package]
name = "vad-masking"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
clap = { workspace = true, features = ["derive"] }
hound = { workspace = true }
meetspace-audacity = { workspace = true }
meetspace-data = { workspace = true }
rodio = { workspace = true }

[dependencies]
meetspace-audio-utils = { workspace = true }
meetspace-vad = { workspace = true, features = ["earshot"] }
