[package]
name = "db-app"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-db-core = { workspace = true }
meetspace-db-migrate = { workspace = true }
meetspace-e2ee = { workspace = true }

base64 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sha2 = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "sqlite-unbundled", "macros"] }
thiserror = { workspace = true }
uuid = { workspace = true, features = ["v4"] }

[features]
default = []
cli = []

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros", "time"] }
