[package]
name = "db-app"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-db-core = { workspace = true }
meetspace-db-migrate = { workspace = true }

serde = { workspace = true, features = ["derive"] }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "sqlite-unbundled", "macros"] }

[features]
default = []
cli = []

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
