[package]
name = "api-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-api-auth = { workspace = true }
meetspace-api-error = { workspace = true }
meetspace-supabase-storage = { workspace = true }

utoipa = { workspace = true }

axum = { workspace = true }
chrono = { workspace = true }
futures-util = { workspace = true }
hmac = { workspace = true }
reqwest = { workspace = true, features = ["json", "query", "stream"] }
sentry = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tower = { workspace = true }
wiremock = { workspace = true }
