[package]
name = "segmentation"
version = "0.1.0"
edition = "2024"

[features]
default = ["onnx"]
onnx = ["dep:meetspace-onnx"]

[dependencies]
meetspace-onnx = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
criterion = { workspace = true }
hound = { workspace = true }
meetspace-data = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

[[bench]]
name = "segmentation_bench"
harness = false
required-features = ["onnx"]
