[package]
name = "template-app"
version = "0.1.0"
edition = "2024"

[dependencies]
askama = { workspace = true }
meetspace-askama-utils = { workspace = true }
serde = { workspace = true, features = ["derive"] }
specta = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
meetspace-template-eval = { workspace = true }

[[test]]
name = "llm_eval"
path = "tests/llm_eval/main.rs"
harness = false
