[package]
name = "cactus"
version = "0.1.0"
edition = "2024"
license = "MIT"

[features]
examples = ["dep:colored"]

[dependencies]
cactus-sys = { git = "https://github.com/cactus-compute/cactus", package = "cactus-sys", rev = "130a60dcd4767a994a34f319d26d02eedb50f293" }

meetspace-cactus-model = { workspace = true }
meetspace-language = { workspace = true }
meetspace-llm-types = { workspace = true }

colored = { version = "3", optional = true }
futures-util = { workspace = true }
tokio = { workspace = true, features = ["rt", "sync"] }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

jsonschema = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
meetspace-data = { workspace = true }
insta = { workspace = true }

[[bench]]
name = "vad"
harness = false

[[example]]
name = "chat"
required-features = ["examples"]
