[package]
name = "supabase-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-observability = { workspace = true }

reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
