[package]
name = "soniox"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-observability = { workspace = true }

reqwest = { workspace = true, features = ["json", "multipart"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["time"] }
