[package]
name = "mobile-bridge"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "mobile_bridge"

[dependencies]
meetspace-db-app = { workspace = true }
meetspace-db-core = { workspace = true }
meetspace-db-execute = { workspace = true }
meetspace-db-migrate = { workspace = true }
meetspace-db-reactive = { workspace = true }

serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "sync", "time"] }
uniffi = { version = "0.31" }

[dev-dependencies]
tempfile = { workspace = true }
