[package]
name = "local-model"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-am = { workspace = true }
meetspace-cactus-model = { workspace = true }
meetspace-file = { workspace = true }
meetspace-model-downloader = { workspace = true }
meetspace-transcribe-soniqo = { workspace = true }
meetspace-whisper-local-model = { workspace = true }

serde = { workspace = true }
specta = { workspace = true }
