[package]
name = "api-ticket"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-api-auth = { workspace = true }
meetspace-api-error = { workspace = true }
meetspace-api-nango = { workspace = true }
meetspace-github-issues = { workspace = true, features = ["utoipa"] }
meetspace-linear = { workspace = true }
meetspace-nango = { workspace = true }
meetspace-ticket-interface = { workspace = true, features = ["utoipa"] }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
