[package]
name = "tauri-plugin-db"
version = "0.1.0"
authors = ["You"]
edition = "2024"
exclude = ["/js", "/node_modules"]
links = "tauri-plugin-db"
description = ""

[dependencies]
meetspace-db-app = { workspace = true }
meetspace-db-core = { workspace = true }
meetspace-db-execute = { workspace = true }
meetspace-db-migrate = { workspace = true }
meetspace-db-reactive = { workspace = true, features = ["specta"] }
meetspace-storage = { workspace = true }
meetspace-tauri-utils = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
specta = { workspace = true, features = ["serde_json"] }
specta-typescript = { workspace = true }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "sqlite-unbundled"] }
tauri = { workspace = true, features = ["test"] }
tauri-specta = { workspace = true, features = ["derive", "typescript"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "sync", "time"] }

[build-dependencies]
tauri-plugin = { workspace = true, features = ["build"] }
