[package]
name = "owhisper-client"
version = "0.0.1"
edition = "2024"

[features]
default = []
local = ["meetspace-audio-utils"]

[dependencies]
meetspace-am = { workspace = true }
meetspace-audio-utils = { workspace = true, optional = true }
meetspace-language = { workspace = true }
meetspace-observability = { workspace = true }
meetspace-ws-client = { workspace = true }
soniox = { workspace = true }

openai-transcription = { workspace = true }
owhisper-interface = { workspace = true }

futures-util = { workspace = true }
reqwest = { workspace = true, features = ["json", "multipart"] }
reqwest-middleware = { workspace = true, features = ["json", "multipart"] }
reqwest-tracing = { workspace = true }
tokio = { workspace = true, features = ["fs"] }
tokio-stream = { workspace = true }

backon = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
meetspace-audio-utils = { workspace = true }
meetspace-data = { workspace = true }

deepgram = { workspace = true, features = ["listen"] }
rodio = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing-subscriber = { workspace = true }
