[package]
name = "db-reactive"
version = "0.1.0"
edition = "2024"

[features]
specta = ["dep:specta"]

[dependencies]
meetspace-db-change = { workspace = true }
meetspace-db-core = { workspace = true }
meetspace-db-execute = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
specta = { workspace = true, optional = true, features = ["serde_json"] }
sqlx = { workspace = true, features = ["runtime-tokio", "sqlite", "sqlite-unbundled"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "sync", "time"] }
uuid = { workspace = true, features = ["v4"] }

[dev-dependencies]
meetspace-cloudsync = { workspace = true }
meetspace-db-migrate = { workspace = true }

anyhow = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "time"] }
