[package]
name = "api-mail"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-api-auth = { workspace = true }
meetspace-api-error = { workspace = true }
meetspace-api-nango = { workspace = true }
meetspace-google-mail = { workspace = true, features = ["utoipa"] }
meetspace-nango = { workspace = true }

axum = { workspace = true }
utoipa = { workspace = true }

serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
