[package]
name = "embedding"
version = "0.1.0"
edition = "2024"

[features]
default = ["onnx"]
onnx = ["dep:meetspace-onnx", "dep:knf-rs"]
coreml = ["onnx", "meetspace-onnx/coreml"]
directml = ["onnx", "meetspace-onnx/directml"]

[dependencies]
knf-rs = { git = "https://github.com/thewh1teagle/pyannote-rs", rev = "e23bd29", package = "knf-rs", optional = true }
meetspace-onnx = { workspace = true, optional = true }

serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
meetspace-data = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
