[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
meetspace-analytics = { workspace = true }
meetspace-api-auth = { workspace = true }
meetspace-api-calendar = { workspace = true }
meetspace-api-env = { workspace = true }
meetspace-api-mail = { workspace = true }
meetspace-api-nango = { workspace = true }
meetspace-api-pyannote = { workspace = true }
meetspace-api-research = { workspace = true }
meetspace-api-subscription = { workspace = true }
meetspace-api-support = { workspace = true }
meetspace-api-ticket = { workspace = true }
meetspace-linear = { workspace = true }
meetspace-llm-proxy = { workspace = true }
meetspace-observability = { workspace = true }
meetspace-transcribe-proxy = { workspace = true }
owhisper-client = { workspace = true }

axum = { workspace = true, features = ["ws"] }
opentelemetry = { workspace = true }
opentelemetry-otlp = { workspace = true }
opentelemetry_sdk = { workspace = true }
rustls = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tower-http = { workspace = true, features = ["trace", "cors", "request-id"] }
tracing = { workspace = true }
tracing-opentelemetry = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

reqwest = { workspace = true, features = ["json"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
url = { workspace = true }

dotenvy = { workspace = true }
envy = { workspace = true }
governor = { workspace = true }
jsonwebtoken = { workspace = true }
sentry = { workspace = true, features = ["tower", "tower-axum-matched-path", "tracing"] }
tower = { workspace = true }
utoipa = { workspace = true }
